language: java
jdk:
  - oraclejdk8

after_success:
  - mvn clean
  - mvn eclipse:eclipse
  - zip -r waterworld .

deploy:
    provider: pages
    local-dir: waterworld.zip
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    on:
      branch: master