language: java
jdk:
  - oraclejdk8

after_success:
  - mvn clean
  - mvn eclipse:eclipse
  - zip waterworld

deploy:
    provider: pages
    local-dir: .
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    on:
      branch: master